version: "3.9"
services:
  db:
    build:
      context: .
      dockerfile: postgres-pgvector
    ports:
      - 5432:5432
    environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=rag
  ollama:
    image: ollama/ollama
    ports:
      - 11434:11434
    entrypoint: ["ollama","serve"]
  r2r:
    image: emrgntcmplxty/r2r
    ports:
      - 8000:8000
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DBNAME=rag
      - OLLAMA_API_BASE=http://ollama:11434
      - CONFIG_OPTION=local_ollama
    depends_on:
      db:
        condition: service_started
      ollama:
        condition: service_started
